# yml template to dockerise a node.js app
version: '3'
services: 
    appservice: 
        build: .
        image: katharinagi/finalproject
        ports: 
            - '4000:3000'
        depends_on: 
            - mongoservice
    mongoservice:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
    mongoexpressservice: 
        image: mongo-express
        restart: unless-stopped
        ports: 
            - '8081:8081'